# Generated by Django 5.0.1 on 2024-02-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
